apiVersion: v1
kind: Secret
metadata:
  name: anscwcserver-secret
data:
  COOKIE_SERVER: emxkdjc2MDgudmNpLmF0dC5jb20K
  COOKIE_SERVER_PORT: NTA1MAo=
  db_user: b3JhYWRtaW4K
  db_password: d2ZlY2FzdEAxMjM0Cg==
  db_url: bjd3ZmMxZDEuYXouM3BjLmF0dC5jb20K
  db_port: MTUyMQo=
  db_sid: cDFjM2Q1NjUK
  db_name: cDFjM2Q1NjUK