apiVersion: v1
kind: Service
metadata:
  name: wfeclient-d2a
  namespace: default
  labels:
    app: WfeClient
    version: 1.18.0
    routeoffer: D2A
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: WfeClient
    version: 1.18.0
    routeoffer: D2A
