apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  generation: 1 
  labels:
    app: WfeClient 
    routeoffer: D2A 
    version: 1.18.0 
  name: wfeclient-d2a 
  namespace: default 
spec: 
  minReadySeconds: 120 
  progressDeadlineSeconds: 2147483647 
  replicas: 1 
  revisionHistoryLimit: 0 
  selector: 
    matchLabels: 
      app: WfeClient 
      routeoffer: D2A 
  strategy: 
    rollingUpdate: 
      maxSurge: 50% 
      maxUnavailable: 50% 
    type: RollingUpdate 
  template: 
    metadata: 
      creationTimestamp: null 
      labels:
        app: WfeClient 
        routeoffer: D2A 
        version: 1.18.0 
    spec: 
      containers: 
      - env: 
        - name: APP_VERSION 
          value: 1.18.0 
        - name: TARGET_ENV 
          value: DEV 
        - name: TEST_VALUE 
          value: "NO" 
        - name: REACT_APP_SERVER_HOST 
          valueFrom: 
            secretKeyRef: 
              key: REACT_APP_SERVER_HOST 
              name: wfecast-client-secrets 
        - name: REACT_APP_IS_PRODUCTION 
          valueFrom: 
            secretKeyRef: 
              key: REACT_APP_IS_PRODUCTION 
              name: wfecast-client-secrets 
        image: 29624wfepocacr.azurecr.io/com.att.wfecst/wfeclient:1.17.0 
        imagePullPolicy: Always 
        name: wfeclient 
        ports: 
        - containerPort: 3000 
          name: http 
          protocol: TCP 
        resources: {} 
        terminationMessagePath: /dev/termination-log 
        terminationMessagePolicy: File 
      dnsPolicy: ClusterFirst 
      restartPolicy: Always 
      schedulerName: default-scheduler 
      securityContext: {} 
      terminationGracePeriodSeconds: 30