resource_group_name  = "29624-eastus2-devops-rg"
storage_account_name = "29624devopsstdgatt02"
container_name       = "adotfstate"
key                  = "prdaksado.tfstate"
region               = "eastus2"